import {
  siAstro,
  siC,
  siCplusplus,
  siCss,
  siDocker,
  siGit,
  siGnubash,
  siGo,
  siGraphql,
  siHtml5,
  siJavascript,
  siJson,
  siKotlin,
  siMarkdown,
  siPython,
  siReact,
  siRust,
  siSwift,
  siToml,
  siTypescript,
  siVuedotjs,
  siYaml,
} from 'simple-icons';

/**
 * Language → simple-icons path data (CC0) for the faint in-block watermark.
 * Build-time only — the SVGs are inlined into the HTML by rehype-code-blocks.
 * Languages without a recognizable logo fall back to text-only.
 */
interface LangIcon {
  path: string;
}

const icon = (si: { path: string }): LangIcon => ({ path: si.path });

export const LANG_ICONS: Record<string, LangIcon> = {
  ts: icon(siTypescript),
  typescript: icon(siTypescript),
  js: icon(siJavascript),
  javascript: icon(siJavascript),
  mjs: icon(siJavascript),
  cjs: icon(siJavascript),
  jsx: icon(siReact),
  tsx: icon(siReact),
  py: icon(siPython),
  python: icon(siPython),
  go: icon(siGo),
  rust: icon(siRust),
  rs: icon(siRust),
  bash: icon(siGnubash),
  sh: icon(siGnubash),
  shell: icon(siGnubash),
  zsh: icon(siGnubash),
  yaml: icon(siYaml),
  yml: icon(siYaml),
  json: icon(siJson),
  jsonc: icon(siJson),
  html: icon(siHtml5),
  css: icon(siCss),
  scss: icon(siCss),
  md: icon(siMarkdown),
  markdown: icon(siMarkdown),
  astro: icon(siAstro),
  docker: icon(siDocker),
  dockerfile: icon(siDocker),
  vue: icon(siVuedotjs),
  kotlin: icon(siKotlin),
  swift: icon(siSwift),
  c: icon(siC),
  cpp: icon(siCplusplus),
  'c++': icon(siCplusplus),
  toml: icon(siToml),
  graphql: icon(siGraphql),
  diff: icon(siGit),
  git: icon(siGit),
};

export const LANG_NAMES: Record<string, string> = {
  js: 'JavaScript',
  javascript: 'JavaScript',
  mjs: 'JavaScript',
  cjs: 'JavaScript',
  ts: 'TypeScript',
  typescript: 'TypeScript',
  jsx: 'JSX',
  tsx: 'TSX',
  html: 'HTML',
  css: 'CSS',
  scss: 'SCSS',
  json: 'JSON',
  jsonc: 'JSON',
  md: 'Markdown',
  markdown: 'Markdown',
  bash: 'Bash',
  sh: 'Shell',
  shell: 'Shell',
  zsh: 'Zsh',
  py: 'Python',
  python: 'Python',
  java: 'Java',
  go: 'Go',
  rust: 'Rust',
  rs: 'Rust',
  cpp: 'C++',
  'c++': 'C++',
  c: 'C',
  yaml: 'YAML',
  yml: 'YAML',
  toml: 'TOML',
  sql: 'SQL',
  graphql: 'GraphQL',
  docker: 'Docker',
  dockerfile: 'Dockerfile',
  astro: 'Astro',
  vue: 'Vue',
  kotlin: 'Kotlin',
  swift: 'Swift',
  diff: 'Diff',
  git: 'Git',
  plaintext: 'Text',
  text: 'Text',
};
